<a href="https://colab.research.google.com/github/Maryann-01/ML-Projects/blob/main/Insurance_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
train_df=pd.read_csv("/content/train_data.csv")
test_df=pd.read_csv("/content/test_data.csv")
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7160 entries, 0 to 7159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer Id         7160 non-null   object
 1   YearOfObservation   7160 non-null   int64
 2   Insured_Period      7160 non-null   float64
 3   Residential         7160 non-null   int64
 4   Building_Painted    7160 non-null   object
 5   Building_Fenced     7160 non-null   object
 6   Garden              7153 non-null   object
 7   Settlement          7160 non-null   object
 8   Building Dimension  7054 non-null   float64
 9   Building_Type       7160 non-null   int64
 10  Date_of_Occupancy   6652 non-null   float64
 11  NumberOfWindows     7160 non-null   object
 12  Geo_Code            7058 non-null   object
 13  Claim               7160 non-null   int64
dtypes: float64(3), int64(4), object(7)
memory usage: 783.3+ KB

In [35]:
train_df.YearOfObservation.value_counts()
len(train_df.YearOfObservation.unique())
len(train_df.Residential.unique())

2

In [36]:
len(train_df.Insured_Period.unique())  #remove this, it has alot of unique values
len(train_df["Building Dimension"].unique())   #2044 unique values
len(train_df["Geo_Code"].unique())  #1308 unique values
train_df.Geo_Code.value_counts()
train_df["NumberOfWindows"].value_counts()

NumberOfWindows
   .    3551
4        939
3        844
5        639
2        363
6        306
7        211
8        116
1         75
>=10      67
9         49
Name: count, dtype: int64

In [37]:
train_df.drop(columns=["Customer Id"],inplace=True)
test_ids = test_df["Customer Id"]
test_df.drop(columns=["Customer Id"],inplace=True)

To handle missing values now

In [38]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7160 entries, 0 to 7159
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YearOfObservation   7160 non-null   int64
 1   Insured_Period      7160 non-null   float64
 2   Residential         7160 non-null   int64
 3   Building_Painted    7160 non-null   object
 4   Building_Fenced     7160 non-null   object
 5   Garden              7153 non-null   object
 6   Settlement          7160 non-null   object
 7   Building Dimension  7054 non-null   float64
 8   Building_Type       7160 non-null   int64
 9   Date_of_Occupancy   6652 non-null   float64
 10  NumberOfWindows     7160 non-null   object
 11  Geo_Code            7058 non-null   object
 12  Claim               7160 non-null   int64
dtypes: float64(3), int64(4), object(6)
memory usage: 727.3+ KB

In [39]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3069 entries, 0 to 3068
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YearOfObservation   3069 non-null   int64
 1   Insured_Period      3069 non-null   float64
 2   Residential         3069 non-null   int64
 3   Building_Painted    3069 non-null   object
 4   Building_Fenced     3069 non-null   object
 5   Garden              3065 non-null   object
 6   Settlement          3069 non-null   object
 7   Building Dimension  3056 non-null   float64
 8   Building_Type       3069 non-null   int64
 9   Date_of_Occupancy   2341 non-null   float64
 10  NumberOfWindows     3069 non-null   object
 11  Geo_Code            3056 non-null   object
dtypes: float64(3), int64(3), object(6)
memory usage: 287.8+ KB

In [40]:
cat_cols_train=train_df.select_dtypes(include=["object"]).columns.tolist()
cat_cols_test=test_df.select_dtypes(include=["object"]).columns.tolist()
num_cols_train=train_df.select_dtypes(include=["int64","float64"]).columns.tolist()
num_cols_test=test_df.select_dtypes(include=["int64","float64"]).columns.tolist()
cat_cols_train

['Building_Painted',
 'Building_Fenced',
 'Garden',
 'Settlement',
 'NumberOfWindows',
 'Geo_Code']

To impute missing values

In [41]:
train_df[num_cols_train]=train_df[num_cols_train].fillna(train_df[num_cols_train].median())
test_df[num_cols_test]=test_df[num_cols_test].fillna(test_df[num_cols_test].median())
train_df[cat_cols_train]=train_df[cat_cols_train].fillna(train_df[cat_cols_train].mode().iloc[0])
test_df[cat_cols_test]=test_df[cat_cols_test].fillna(test_df[cat_cols_test].mode().iloc[0])
train_df.info()
# test_df[cat_cols_test]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7160 entries, 0 to 7159
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YearOfObservation   7160 non-null   int64
 1   Insured_Period      7160 non-null   float64
 2   Residential         7160 non-null   int64
 3   Building_Painted    7160 non-null   object
 4   Building_Fenced     7160 non-null   object
 5   Garden              7160 non-null   object
 6   Settlement          7160 non-null   object
 7   Building Dimension  7160 non-null   float64
 8   Building_Type       7160 non-null   int64
 9   Date_of_Occupancy   7160 non-null   float64
 10  NumberOfWindows     7160 non-null   object
 11  Geo_Code            7160 non-null   object
 12  Claim               7160 non-null   int64
dtypes: float64(3), int64(4), object(6)
memory usage: 727.3+ KB

Next up, scaling..if necessary

In [42]:
train_df.describe()

,YearOfObservation,Insured_Period,Residential,Building Dimension,Building_Type,Date_of_Occupancy,Claim
count,7160.000000,7160.000000,7160.000000,7160.000000,7160.000000,7160.000000,7160.000000
mean,2013.669553,0.909758,0.305447,1871.873184,2.186034,1964.849721,0.228212
std,1.383769,0.239756,0.460629,2263.296186,0.940632,34.730347,0.419709
min,2012.000000,0.000000,0.000000,1.000000,1.000000,1545.000000,0.000000
25%,2012.000000,0.997268,0.000000,531.500000,2.000000,1960.000000,0.000000
50%,2013.000000,1.000000,0.000000,1083.000000,2.000000,1970.000000,0.000000
75%,2015.000000,1.000000,1.000000,2250.000000,3.000000,1980.000000,0.000000
max,2016.000000,1.000000,1.000000,20940.000000,4.000000,2016.000000,1.000000

Before we scale, we need to convert our object columns to int using one hot encoding

In [43]:

# train_df=pd.get_dummies(train_df,columns=cat_cols_train, drop_first=True)
# test_df=pd.get_dummies(test_df,columns=cat_cols_test, drop_first=True)
# test_df

print("Before Encoding:", train_df.dtypes)
train_df = pd.get_dummies(train_df, columns=cat_cols_train, drop_first=True, dtype=int)
test_df=pd.get_dummies(test_df,columns=cat_cols_test, drop_first=True,dtype=int)

Before Encoding: YearOfObservation       int64
Insured_Period        float64
Residential             int64
Building_Painted       object
Building_Fenced        object
Garden                 object
Settlement             object
Building Dimension    float64
Building_Type           int64
Date_of_Occupancy     float64
NumberOfWindows        object
Geo_Code               object
Claim                   int64
dtype: object

In [50]:
# test_df.head()
train_df.head()

,YearOfObservation,Insured_Period,Residential,Building Dimension,Building_Type,Date_of_Occupancy,Claim,Building_Painted_V,Building_Fenced_V,Garden_V,...,Geo_Code_95428,Geo_Code_95488,Geo_Code_95500,Geo_Code_95539,Geo_Code_95555,Geo_Code_95563,Geo_Code_95582,Geo_Code_95585,Geo_Code_95598,Geo_Code_95607
0,2013,1.0,0,290.0,1,1960.0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2015,1.0,0,490.0,1,1850.0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2014,1.0,0,595.0,1,1960.0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,2013,1.0,0,2840.0,1,1960.0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,2014,1.0,0,680.0,1,1800.0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

Now , we scale seeing how the std looks

In [64]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
# scaler.fit_transform()
# if "Claim" in train_df.columns:
#     print("Target column is present.")
# else:
#     print("Target column is missing.")

X_train=train_df.drop(columns=["Claim"])
y_train=train_df["Claim"]


X_test = test_df.reindex(columns=X_train.columns, fill_value=0)
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [53]:
X_test_scaled

array([[-0.48389585,  0.3764189 , -0.66315517, ..., -0.03128275,
        -0.01181881, -0.01671549],
       [ 1.68424825,  0.36502217, -0.66315517, ..., -0.03128275,
        -0.01181881, -0.01671549],
       [-0.48389585, -2.25201129, -0.66315517, ..., -0.03128275,
        -0.01181881, -0.01671549],
       ...,
       [-1.20661055,  0.3764189 , -0.66315517, ..., -0.03128275,
        -0.01181881, -0.01671549],
       [-0.48389585,  0.3764189 , -0.66315517, ..., -0.03128275,
        -0.01181881, -0.01671549],
       [-1.20661055,  0.3764189 , -0.66315517, ..., -0.03128275,
        -0.01181881, -0.01671549]])

Light boosting model

In [63]:
import lightgbm as lgb
from sklearn.metrics import roc_auc_score


model = lgb.LGBMClassifier(n_estimators=200, learning_rate=0.05, random_state=42)
model.fit(X_train_scaled, y_train)


y_pred_proba = model.predict_proba(X_test_scaled)[:, 1]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Number of positive: 1634, number of negative: 5526
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006430 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 717
[LightGBM] [Info] Number of data points in the train set: 7160, number of used features: 99
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.228212 -> initscore=-1.218433
[LightGBM] [Info] Start training from score -1.218433

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [62]:
submission = pd.DataFrame({"Customer Id": test_ids, "Claim": y_pred_proba})


submission.to_csv("submission.csv", index=False)

print("Submission file ready for upload!")

Submission file ready for upload!